window.esdocSearchIndex = [
  [
    "remote-device-logger/remote-device-logger/index.js~remotedevicelogger",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html",
    "<span>RemoteDeviceLogger</span> <span class=\"search-result-import-path\">remote-device-logger/remote-device-logger/index.js</span>",
    "class"
  ],
  [
    "remote-device-logger/index.js",
    "file/remote-device-logger/index.js.html",
    "remote-device-logger/index.js",
    "file"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#_catchallerrors",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-_catchAllErrors",
    "remote-device-logger/index.js~RemoteDeviceLogger#_catchAllErrors",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#_connectwebsocket",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-_connectWebSocket",
    "remote-device-logger/index.js~RemoteDeviceLogger#_connectWebSocket",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#_connection",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-member-_connection",
    "remote-device-logger/index.js~RemoteDeviceLogger#_connection",
    "member"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#_createelement",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-_createElement",
    "remote-device-logger/index.js~RemoteDeviceLogger#_createElement",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#_element",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-member-_element",
    "remote-device-logger/index.js~RemoteDeviceLogger#_element",
    "member"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#_logpool",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-member-_logPool",
    "remote-device-logger/index.js~RemoteDeviceLogger#_logPool",
    "member"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#_stdout",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-member-_stdout",
    "remote-device-logger/index.js~RemoteDeviceLogger#_stdout",
    "member"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#constructor",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-constructor-constructor",
    "remote-device-logger/index.js~RemoteDeviceLogger#constructor",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#hide",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-hide",
    "remote-device-logger/index.js~RemoteDeviceLogger#hide",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#log",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-log",
    "remote-device-logger/index.js~RemoteDeviceLogger#log",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#print",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-print",
    "remote-device-logger/index.js~RemoteDeviceLogger#print",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#sendlog",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-sendLog",
    "remote-device-logger/index.js~RemoteDeviceLogger#sendLog",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#show",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-show",
    "remote-device-logger/index.js~RemoteDeviceLogger#show",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#toggle",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-toggle",
    "remote-device-logger/index.js~RemoteDeviceLogger#toggle",
    "method"
  ],
  [
    "remote-device-logger/index.js~remotedevicelogger#writetoelement",
    "class/remote-device-logger/index.js~RemoteDeviceLogger.html#instance-method-writeToElement",
    "remote-device-logger/index.js~RemoteDeviceLogger#writeToElement",
    "method"
  ]
]